### ISSUE TITLE
Current version of linuxkit has no build option

### ISSUE THREAD

**Issue by martinborgman** [linuxkit/kubernetes#12]
**Description**
Invoking make produces the following error:

$ make all KUBE_RUNTIME=cri-containerd
curl -L -o kube-weave.yaml https://cloud.weave.works/k8s/v1.8/net?v=v2.0.5
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   274  100   274    0     0    254      0  0:00:01  0:00:01 --:--:--   254
100  6956  100  6956    0     0   5296      0  0:00:01  0:00:01 --:--:--  5296
linuxkit build -name kube-master -format iso-efi yml/kube.yml yml/cri-containerd.yml yml/cri-containerd-master.yml yml/weave.yml
"build" is not valid command.

USAGE: linuxkit [options] COMMAND

Commands:
  metadata    Metadata utilities
  push        Push a VM image to a cloud or image store
  run         Run a VM image on a local hypervisor or remote cloud
  version     Print version information
  help        Print this message

Run 'linuxkit COMMAND --help' for more information on the command

Options:
  -q	Quiet execution
  -v	Verbose execution
make: *** [kube-master.iso] Error 1
$

**Steps to reproduce the issue:**

Just run make again

**Describe the results you received:**

See above

**Describe the results you expected:**

Successful build

**Additional information you deem important (e.g. issue happens only occasionally):**
$ linuxkit version
linuxkit version 0.0
commit: 92947c9c417d703c491711f23d00ceb9f53df5b0
$

I assume you now need buildkit to build images.

**Comment by justincormack** [comment]
The current version does have build. How did you install LinuxKit?

**Comment by w9n** [comment]
You have to upgrade your linuxkit cli because the script switched to `linuxkit build` which is missing in the usage output.

**Comment by ijc** [comment]
> commit: 92947c9c417d703c491711f23d00ceb9f53df5b0

But:
```
$ pwd
/home/ijc/development/Docker/LinuxKit/gocode/src/github.com/linuxkit/linuxkit
$ git remote update -p
Fetching origin
Fetching ijc
$ git show 92947c9c417d703c491711f23d00ceb9f53df5b0
fatal: bad object 92947c9c417d703c491711f23d00ceb9f53df5b0
```

So I don't know what version this is or where it came from.

Please update to the latest `linuxkit` binary (newer than https://github.com/linuxkit/linuxkit/pull/2761) which does have the `build` subcommand.

Closing for now, if the upgrade doesn't help we can reopen and revisit.

**Comment by martinborgman** [comment]
The linuxkit version was installed using homebrew with `--HEAD`.
The installed version was `linuxkit/HEAD-0df77e4`.

However there is a rather annoying issue with homebrew. If you ever install something using `--HEAD`, it doesn't get updated using brew update && brew upgrade.

I reinstalled linuxkit and the current version is `linuxkit/HEAD-c6fad9f` or:

```Shell
$ linuxkit version
linuxkit version 0.0
commit: c6fad9f76b9dd5208a3e9b70785de7d77a2a1713
```

This version of linuxkit has the build option so you can close this issue.

**Comment by justincormack** [comment]
Yes, you need to do `brew reinstall --HEAD linuxkit` it is annoying. We will do a release version soon which should make this easier...
