### ISSUE TITLE
containerised kubelet going away

### ISSUE THREAD

**Issue by justincormack** [linuxkit/kubernetes#88]
https://github.com/kubernetes/kubernetes/pull/74267

Not sure what the best way of dealing with this is.

**Comment by deitch** [comment]
Do we use the `--containerized` flag? It doesn't look like it based on https://github.com/linuxkit/kubernetes/blob/master/pkg/kubelet/kubelet.sh#L97

**Comment by justincormack** [comment]
AH ok we may be fine then.

**Comment by justincormack** [comment]
closing for now.
